name = "Creatine"
author = "alpinesystem"
version = "1.4.1"
description = "An extensive Create modpack that aims to include almost every extension that works together. Also includes other stuff my friends wanted."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e02e208357b93ca039e0effdf5603642634e26ee533560152d01034e3476bb8c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"

[options]
acceptable-game-versions = []
