name = "Creatine"
author = "alpinesystem"
version = "1.3.1"
description = "An extensive Create modpack that aims to include almost every extension that works together. Also includes other stuff my friends wanted."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "15709d192bc322be480dd55560c7995f88e904f302f8b323655c245741cadc9f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"

[options]
acceptable-game-versions = []
