# Maximum allowed length for pronoun preference (inclusive)
# default: 16
maxLength = 16
# The default value used for players that have not set their pronoun preference yet
# default: 
defaultPronouns = ""
# Whether to provide basic suggestions for the /pronouns command
# default: false
suggestBasicPronouns = false
# The suggestions used when suggestBasicPronouns is true
basicPronouns = ["he/him", "she/her", "they/them"]
# Whether to provide suggestions for custom pronouns and clearing pronouns (<custom>, <blank>)
# default: false
suggestFakePrompts = false
